### ISSUE TITLE
Plex server access

### ISSUE THREAD

**Issue by jshurak** [nlopez/k8s_home#8]
You have a commit about ditching metallb for clusterip in your pms service.  I'm having issues getting plex fully up and running and I'm wondering if you ran into something similar.  Basically plex comes up, but the server is only accessible from the server's web app.  Any remote plex client cannot connect.  They can see it in the server list, but not connect.  Did you happen to run into anything like this?

**Comment by nlopez** [comment]
Hey @jshurak - my reasons for ditching metallb had to do with some trouble getting it working in its layer 2 mode after relaunching my k8s cluster. 

Since I'm already using [kube-router](https://github.com/cloudnativelabs/kube-router) and sending BGP announcements to my gateway, I use the [clusterIP defined here](https://github.com/nlopez/k8s_home/blob/4414612a68a8020da5f3c87d1c6bc696d4f4fec7/media/pms/service.yaml#L10) when setting up port forwarding rules on my gw. I forward from 32400 external to `10.102.213.52:32400`.

I think the simplest way to get Plex working on k8s is to use a [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport). This doesn't require any special CNI configuration/capabilities.
